//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HienThiHoaDon
    {
        public string TenSach { get; set; }
        public long Gia { get; set; }
        public string Anh { get; set; }
        public string TenKhachHang { get; set; }
        public bool DaThanhToan { get; set; }
        public long ThanhTien { get; set; }
        public int SoLuongMua { get; set; }
        public string MaHoaDon { get; set; }
    }
}
